var pontos = {
	1: {
		quem: "Francisco",
		oque: "vendedor de frutas",
		desde: "2005",
		quando: "segunda a sexta",
		de: "6", 
		ate: "18",
		mora: "em Duque de Caxias",
		posX: 455,
		posY: 630,
		box: 0
	},
	2: {
		quem: "Wilson",
		oque: "vendedor de discos e mídias usadas",
		desde: "2007",
		quando: "segunda a sexta",
		de: "10", 
		ate: "18",
		mora: "na Praça Mauá",	
		posX: 408,
		posY: 828,
		box: 0		
	},
	3: {
		quem: "Idelmo",		
		oque: "sapateiro e antiquário",
		desde: "1989",
		quando: "segunda a sexta",
		de: "9:30", 
		ate: "18",
		mora: "na Gamboa",
		posX: 360,
		posY: 1060,
		box: 0
	},
	4: {
		quem: "-",		
		oque: "sorveteiro",
		desde: "2001",
		quando: "segunda a sexta",
		de: "9:30", 
		ate: "18",
		mora: "-",
		posX: 586,
		posY: 1244,
		box: 2		
	},
	5: {	
		quem: "José Carlos",		
		oque: "vendedor de amendoim",
		desde: "2007",
		quando: "segunda a sábado",
		de: "10:30", 
		ate: "18",
		mora: "em Bento Ribeiro",
		posX: 681,
		posY: 1333,
		box: 2
	},
	6: {
		quem: "-",		
		oque: "verdureiro",
		desde: "1992",
		quando: "segunda a sexta",
		de: "9", 
		ate: "18",
		mora: "-",
		posX: 550,
		posY: 1405,
		box: 0				
	},
	7: {
		quem: "Maria",
		oque: "vendedora de doces e de bebidas",
		desde: "1972",
		quando: "segunda a domingo",
		de: "9", 
		ate: "20",
		mora: "-",
		posX: 536,
		posY: 1360,
		box: 0		
	},
	8: {
		quem: "Ricardo",
		oque: "vende frutas",
		desde: "2008",
		quando: "segunda a sexta",
		de: "13", 
		ate: "22",
		mora: "nop Jardim América",
		posX: 355,
		posY: 1308,
		box: 0		
	},
	9: {
		quem: "Nei",
		oque: "vende frutas",
		desde: "1977",
		quando: "segunda a sexta",
		de: "10", 
		ate: "20",
		mora: "em Pilares",
		posX: 345,
		posY: 1111,
		box: 0	
	},
	10: {
		quem: "Celio",
		oque: "vende jornais e revistas",
		desde: "1972",
		quando: "segunda a sábado",
		de: "4:30", 
		ate: "16",
		mora: "-",
		posX: 366,
		posY: 1000,
		box: 0		
	},
	11: {
		quem: "Américo",
		oque: "vende biscoito e balas",
		desde: "1992",
		quando: "segunda a sexta",
		de: "6", 
		ate: "17",
		mora: "na Praça Tiradentes",
		posX: 680,
		posY: 665,
		box: 2		
	},
	12: {
		quem: "Nova Lapa Jazz",
		oque: "show gratuito",
		desde: "há 4 meses",
		quando: "segunda a sexta",
		de: "6", 
		ate: "17",
		mora: "-",
		posX: 250,
		posY: 1255,
		box: 0		
	}		
}